
CREATE TABLE IDS  (
  TABLE_NAME character varying(20) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);


CREATE TABLE LETTNLOGINLOG
(
	LOG_ID                char(20)  NOT NULL ,
	CONECT_ID             character varying(20)  NULL ,
	CONECT_IP             character varying(23)  NULL ,
	CONECT_MTHD           char(4)  NULL ,
	ERROR_OCCRRNC_AT      char(1)  NULL ,
	ERROR_CODE            char(3)  NULL ,
	CREAT_DT              DATE  NULL ,
CONSTRAINT  LETTNLOGINLOG_PK PRIMARY KEY (LOG_ID)
);


CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM character varying(60) ,
  CL_CODE_DC character varying(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;

CREATE TABLE LETTCCMMNCODE (
  CODE_ID character varying(6) NOT NULL,
  CODE_ID_NM character varying(60) ,
  CODE_ID_DC character varying(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;

CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID character varying(6) NOT NULL,
  CODE character varying(15) NOT NULL,
  CODE_NM character varying(60) ,
  CODE_DC character varying(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;

CREATE TABLE LETTNORGNZTINFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM character varying(20) NOT NULL,
  ORGNZT_DC character varying(100) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;

CREATE TABLE LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM character varying(60) NOT NULL,
  GROUP_CREAT_DE char(30) NOT NULL,
  GROUP_DC character varying(100) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;

CREATE TABLE LETTNAUTHORINFO (
  AUTHOR_CODE character varying(30) DEFAULT '' NOT NULL,
  AUTHOR_NM character varying(60) NOT NULL,
  AUTHOR_DC character varying(200) ,
  AUTHOR_CREAT_DE char(30) NOT NULL,
  CONSTRAINT LETTNAUTHORINFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;

CREATE TABLE LETTNROLES_HIERARCHY (
  PARNTS_ROLE character varying(30) NOT NULL,
  CHLDRN_ROLE character varying(30) NOT NULL,
  CONSTRAINT LETTNROLES_HIERARCHY_PK PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_2 FOREIGN KEY (CHLDRN_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNROLES_HIERARCHY_ibfk_1 FOREIGN KEY (PARNTS_ROLE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;

CREATE TABLE LETTNROLEINFO (
  ROLE_CODE character varying(50) DEFAULT '' NOT NULL,
  ROLE_NM character varying(60) NOT NULL,
  ROLE_PTTRN character varying(300) ,
  ROLE_DC character varying(200) ,
  ROLE_TY character varying(80) ,
  ROLE_SORT character varying(10) ,
  ROLE_CREAT_DE char(30) NOT NULL,
  CONSTRAINT LETTNROLEINFO_PK PRIMARY KEY (ROLE_CODE)
) ;

CREATE TABLE LETTNAUTHORROLERELATE (
  AUTHOR_CODE character varying(30) NOT NULL,
  ROLE_CODE character varying(50) NOT NULL,
  CREAT_DT DATE ,
  CONSTRAINT LETTNAUTHORROLERELATE_PK PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_2 FOREIGN KEY (ROLE_CODE) REFERENCES LETTNROLEINFO (ROLE_CODE) ON DELETE CASCADE,
  CONSTRAINT LETTNAUTHORROLERELATE_ibfk_1 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE) ON DELETE CASCADE
) ;

CREATE TABLE LETTNGNRLMBER (
  MBER_ID character varying(20) DEFAULT '' NOT NULL,
  PASSWORD character varying(200) NOT NULL,
  PASSWORD_HINT character varying(100) NOT NULL,
  PASSWORD_CNSR character varying(100) NOT NULL,
  IHIDNUM character varying(200) ,
  MBER_NM character varying(50) NOT NULL,
  ZIP character varying(6) ,
  ADRES character varying(100) ,
  AREA_NO character varying(4) ,
  MBER_STTUS character varying(15) ,
  DETAIL_ADRES character varying(100) ,
  END_TELNO character varying(4) ,
  MBTLNUM character varying(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM character varying(20) ,
  MBER_EMAIL_ADRES character varying(50) ,
  MIDDLE_TELNO character varying(4) ,
  SBSCRB_DE DATE ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;

CREATE TABLE LETTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID character varying(20) NOT NULL,
  MBER_TY_CODE character varying(15) ,
  AUTHOR_CODE character varying(30) NOT NULL,
  CONSTRAINT LETTNEMPLYRSCRTYESTBS_PK PRIMARY KEY (SCRTY_DTRMN_TRGET_ID),
  CONSTRAINT LETTNEMPLYRSCRTYESTBS_ibfk_4 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE)
) ;

CREATE TABLE LETTNTMPLATINFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM character varying(255) ,
  TMPLAT_COURS character varying(2000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID character varying(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT LETTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;

CREATE TABLE LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL,
  BBS_NM character varying(255) NOT NULL,
  BBS_INTRCN character varying(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID character varying(20) NOT NULL,
  FRST_REGIST_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE LETTNBBSUSE (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;

CREATE TABLE LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ character varying(2000) ,
  NTT_CN text,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO character varying(10) ,
  ANSWER_LC character varying(8) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID character varying(20) ,
  NTCR_NM character varying(20) ,
  PASSWORD character varying(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID character varying(20) NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;

CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;

CREATE TABLE LETTNEMPLYRINFO (
  EMPLYR_ID character varying(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM character varying(60) NOT NULL,
  PASSWORD character varying(200) NOT NULL,
  EMPL_NO character varying(20) ,
  IHIDNUM character varying(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM character varying(20) ,
  HOUSE_ADRES character varying(100) ,
  PASSWORD_HINT character varying(100) NOT NULL,
  PASSWORD_CNSR character varying(100) NOT NULL,
  HOUSE_END_TELNO character varying(4) ,
  AREA_NO character varying(4) ,
  DETAIL_ADRES character varying(100) ,
  ZIP character varying(6) ,
  OFFM_TELNO character varying(20) ,
  MBTLNUM character varying(20) ,
  EMAIL_ADRES character varying(50) ,
  OFCPS_NM character varying(60) ,
  HOUSE_MIDDLE_TELNO character varying(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE character varying(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE character varying(20) ,
  SBSCRB_DE DATE ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;

CREATE TABLE LETTCZIP (
  ZIP character varying(6) NOT NULL,
  SN numeric(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM character varying(20) ,
  SIGNGU_NM character varying(20) ,
  EMD_NM character varying(60) ,
  LI_BULD_NM character varying(60) ,
  LNBR_DONG_HO character varying(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTCZIP_PK PRIMARY KEY (ZIP,SN)
) ;


CREATE TABLE LETTNBANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM character varying(60) NOT NULL,
  LINK_URL character varying(255) NOT NULL,
  BANNER_IMAGE character varying(60) NOT NULL,
  BANNER_DC character varying(200) ,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID character varying(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  BANNER_IMAGE_FILE character varying(60) ,
  SORT_ORDR numeric(8,0) ,
  CONSTRAINT LETTNBANNER_PK PRIMARY KEY (BANNER_ID)
) ;

CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID character varying(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO character varying(10) ,
  JURIRNO character varying(13) ,
  CMPNY_NM character varying(60) NOT NULL,
  CXFC character varying(50) ,
  ZIP character varying(6) ,
  ADRES character varying(100) ,
  ENTRPRS_MIDDLE_TELNO character varying(4) ,
  FXNUM character varying(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM character varying(50) ,
  APPLCNT_IHIDNUM character varying(200) ,
  SBSCRB_DE DATE ,
  ENTRPRS_MBER_STTUS character varying(15) ,
  ENTRPRS_MBER_PASSWORD character varying(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT character varying(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR character varying(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES character varying(100) ,
  ENTRPRS_END_TELNO character varying(4) ,
  AREA_NO character varying(4) ,
  APPLCNT_EMAIL_ADRES character varying(50) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;

CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATE NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;

CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN character varying(10) NOT NULL,
  FILE_STRE_COURS character varying(2000) NOT NULL,
  STRE_FILE_NM character varying(255) NOT NULL,
  ORIGNL_FILE_NM character varying(255) ,
  FILE_EXTSN character varying(20) NOT NULL,
  FILE_CN text,
  FILE_SIZE character varying(8) ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;

CREATE TABLE LETTNFAQINFO (
  FAQ_ID char(20) NOT NULL,
  QESTN_SJ character varying(255) ,
  QESTN_CN character varying(2500) ,
  ANSWER_CN character varying(2500) ,
  RDCNT numeric(10,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID character varying(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID character varying(20) NOT NULL,
  ATCH_FILE_ID char(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  CONSTRAINT LETTNFAQINFO_PK PRIMARY KEY (FAQ_ID),
  CONSTRAINT LETTNFAQINFO_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;

CREATE TABLE LETTNINDVDLINFOPOLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN character varying(2500) ,
  INDVDL_INFO_POLICY_AGRE_AT char(1) ,
  FRST_REGISTER_ID character varying(20) ,
  FRST_REGIST_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  INDVDL_INFO_POLICY_NM character varying(255) ,
  CONSTRAINT LETTNINDVDLINFOPOLICY_PK PRIMARY KEY (INDVDL_INFO_POLICY_ID)
) ;

CREATE TABLE LETTNPROGRMLIST (
  PROGRM_FILE_NM character varying(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH character varying(100) NOT NULL,
  PROGRM_KOREAN_NM character varying(60) ,
  PROGRM_DC character varying(200) ,
  URL character varying(100) NOT NULL,
  CONSTRAINT LETTNPROGRMLIST_PK PRIMARY KEY (PROGRM_FILE_NM)
) ;

CREATE TABLE LETTNMENUINFO (
  MENU_NM character varying(60) NOT NULL,
  PROGRM_FILE_NM character varying(60) NOT NULL,
  MENU_NO numeric(20,0) NOT NULL,
  UPPER_MENU_NO numeric(20,0) ,
  MENU_ORDR numeric(5,0) NOT NULL,
  MENU_DC character varying(250) ,
  RELATE_IMAGE_PATH character varying(100) ,
  RELATE_IMAGE_NM character varying(60) ,
  CONSTRAINT LETTNMENUINFO_PK PRIMARY KEY (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_2 FOREIGN KEY (UPPER_MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO),
  CONSTRAINT LETTNMENUINFO_ibfk_1 FOREIGN KEY (PROGRM_FILE_NM) REFERENCES LETTNPROGRMLIST (PROGRM_FILE_NM) ON DELETE CASCADE
) ;

CREATE TABLE LETTNMENUCREATDTLS (
  MENU_NO numeric(20,0) NOT NULL,
  AUTHOR_CODE character varying(30) NOT NULL,
  MAPNG_CREAT_ID character varying(30) ,
  CONSTRAINT LETTNMENUCREATDTLS_PK PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_3 FOREIGN KEY (AUTHOR_CODE) REFERENCES LETTNAUTHORINFO (AUTHOR_CODE),
  CONSTRAINT LETTNMENUCREATDTLS_ibfk_1 FOREIGN KEY (MENU_NO) REFERENCES LETTNMENUINFO (MENU_NO) ON DELETE CASCADE
) ;

CREATE TABLE LETTNQAINFO (
  QA_ID char(20) NOT NULL,
  QESTN_SJ character varying(255) ,
  QESTN_CN character varying(2500) ,
  WRITNG_DE char(20) ,
  RDCNT numeric(10,0) ,
  EMAIL_ADRES character varying(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  QNA_PROCESS_STTUS_CODE char(1) ,
  WRTER_NM character varying(20) ,
  ANSWER_CN character varying(2500) ,
  WRITNG_PASSWORD character varying(20) ,
  ANSWER_DE char(20) ,
  EMAIL_ANSWER_AT char(1) ,
  AREA_NO character varying(4) ,
  MIDDLE_TELNO character varying(4) ,
  END_TELNO character varying(4) ,
  CONSTRAINT LETTNQAINFO_PK PRIMARY KEY (QA_ID)
) ;


CREATE TABLE LETTNQUSTNRTMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY character varying(100) ,
  QUSTNR_TMPLAT_DC character varying(2000) ,
  QUSTNR_TMPLAT_PATH_NM character varying(100) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  QUSTNR_TMPLAT_IMAGE_INFO oid,
  CONSTRAINT LETTNQUSTNRTMPLAT_PK PRIMARY KEY (QUSTNR_TMPLAT_ID)
) ;


CREATE TABLE LETTNQESTNRINFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ character varying(255) ,
  QUSTNR_PURPS character varying(1000) ,
  QUSTNR_WRITNG_GUIDANCE_CN character varying(2000) ,
  QUSTNR_TRGET character varying(1000) ,
  QUSTNR_BGNDE char(20) ,
  QUSTNR_ENDDE char(20) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNQESTNRINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID),
  CONSTRAINT LETTNQESTNRINFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRTMPLAT (QUSTNR_TMPLAT_ID)
) ;

CREATE TABLE LETTNQUSTNRQESITM (
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN numeric(10,0) ,
  QESTN_TY_CODE char(1) ,
  QESTN_CN character varying(2500) ,
  MXMM_CHOISE_CO numeric(5,0) ,
  FRST_REGIST_PNTTM DATE NOT NULL,
  FRST_REGISTER_ID character varying(20) NOT NULL,
  LAST_UPDT_PNTTM DATE NOT NULL,
  LAST_UPDUSR_ID character varying(20) NOT NULL,
  CONSTRAINT LETTNQUSTNRQESITM_PK PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT LETTNQUSTNRQESITM_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES LETTNQESTNRINFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;

CREATE TABLE LETTNQUSTNRIEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID character varying(20) NOT NULL,
  IEM_SN numeric(5,0) ,
  IEM_CN character varying(1000) ,
  ETC_ANSWER_AT char(1) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNQUSTNRIEM_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID),
  CONSTRAINT LETTNQUSTNRIEM_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRQESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;


CREATE TABLE LETTNQUSTNRRESPONDINFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) ,
  OCCP_TY_CODE character varying(1) ,
  RESPOND_NM character varying(50) ,
  BRTHDY char(20) ,
  AREA_NO character varying(4) ,
  MIDDLE_TELNO character varying(4) ,
  END_TELNO character varying(4) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNQUSTNRRESPONDINFO_PK PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID),
  CONSTRAINT LETTNQUSTNRRESPONDINFO_ibfk_1 FOREIGN KEY (QUSTNR_TMPLAT_ID, QESTNR_ID) REFERENCES LETTNQESTNRINFO (QUSTNR_TMPLAT_ID, QESTNR_ID)
) ;

CREATE TABLE LETTNQUSTNRRSPNSRESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN character varying(1000) ,
  ETC_ANSWER_CN character varying(1000) ,
  RESPOND_NM character varying(50) ,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  QUSTNR_IEM_ID character varying(20) ,
  CONSTRAINT LETTNQUSTNRRSPNSRESULT_PK PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID),
  CONSTRAINT LETTNQUSTNRRSPNSRESULT_ibfk_1 FOREIGN KEY (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID) REFERENCES LETTNQUSTNRQESITM (QESTNR_ID, QUSTNR_QESITM_ID, QUSTNR_TMPLAT_ID)
) ;


CREATE TABLE LETTNSTPLATINFO (
  USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM character varying(100) ,
  USE_STPLAT_CN text,
  INFO_PROVD_AGRE_CN text,
  FRST_REGIST_PNTTM DATE ,
  FRST_REGISTER_ID character varying(20) ,
  LAST_UPDT_PNTTM DATE ,
  LAST_UPDUSR_ID character varying(20) ,
  CONSTRAINT LETTNSTPLATINFO_PK PRIMARY KEY (USE_STPLAT_ID)
) ;

CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;